#!/usr/bin/env python
# coding: utf-8

import os
import sys
import subprocess

def run_command(command):
    print(f"[*] Executing: {command}")
    try:
        subprocess.run(command, shell=True, check=True)
    except subprocess.CalledProcessError:
        print(f"[!] Error executing: {command}")
        sys.exit(1)

def main():
    if len(sys.argv) < 2:
        print_usage()
        return

    mode = sys.argv[1]

    # STAGE 1: Preprocessing and Triplet Feature Extraction
    if mode == 'preprocess':
        if len(sys.argv) != 6:
            print("Usage: python OmniSV.py preprocess <vcf_path> <bam_path> <output_dir> <reference>")
            return
        
        vcf_path, bam_path, out_dir, ref_fa = sys.argv[2], sys.argv[3], sys.argv[4], sys.argv[5]
        
        # 1. Parse VCF genotypes
        run_command(f"bash parse_vcf.sh {vcf_path} {out_dir}")
        
        # 2. Extract standardized CIGAR images (1024 width) and consensus sequences (2000bp)
        run_command(f"python data_prepare/data_main.py --bam {bam_path} --vcf {vcf_path} --ref {ref_fa} --out {out_dir}")
        
        # 3. Multimodal deep representation encoding
        run_command(f"python feature_extract/evo2_encoder.py --data_dir {out_dir}")
        run_command(f"python feature_extract/alphagenome_encoder.py --data_dir {out_dir}")
        run_command(f"python feature_extract/image_encoder.py --data_dir {out_dir}")
        print(f"[+] Preprocessing complete. Data ready in {out_dir}")

    # STAGE 2: Multi-Granularity Optimization Training
    elif mode == 'train':
        if len(sys.argv) != 7:
            print("Usage: python OmniSV.py train <label_json> <feat_dir> <save_dir> <model_name> <gpu_id>")
            return
        
        label_json, feat_dir, save_dir, model_name, gpu_id = sys.argv[2], sys.argv[3], sys.argv[4], sys.argv[5], sys.argv[6]

        # Automatically aligns with the direct feature directories generated by the three encoders
        cmd = (f"python model_trainer.py "
               f"--label_json {label_json} --syn_dir {feat_dir} --evo_dir {feat_dir} --omics_dir {feat_dir} "
               f"--save_dir {save_dir} --model_name {model_name} --device cuda:{gpu_id} "
               f"--epochs 50 --batch_size 64")
        run_command(cmd)

    # STAGE 3: Downstream Filtering and VCF Revision
    elif mode == 'refine':
        if len(sys.argv) != 7:
            print("Usage: python OmniSV.py refine <feat_dir> <model_path> <vcf_to_revise> <output_vcf> <gpu_id>")
            return

        feat_dir, model_path, raw_vcf, out_vcf, gpu_id = sys.argv[2], sys.argv[3], sys.argv[4], sys.argv[5], sys.argv[6]
        temp_csv = os.path.join(feat_dir, "predictions.csv")
        
        # Predictor consumes the exact same structured feature directory as the trainer
        cmd = (f"python model_predictor.py --model_path {model_path} "
               f"--syn_dir {feat_dir} --evo_dir {feat_dir} --omics_dir {feat_dir} "
               f"--output {temp_csv} --gpu {gpu_id}")
        run_command(cmd)
        
        run_command(f"python revise_vcf.py --vcf {raw_vcf} --csv {temp_csv} --out {out_vcf}")

    else:
        print_usage()

def print_usage():
    print("\n" + "="*70)
    print("Omni-SV: Multi-modal Genomic SV Refiner Pipeline")
    print("="*70)
    print("\n[STEP 1] Preprocess:")
    print("    python OmniSV.py preprocess <vcf> <bam> <out_dir> <ref.fa>")
    print("\n[STEP 2] Train:")
    print("    python OmniSV.py train <labels.json> <out_dir> <save_dir> <model_name> <gpu_id>")
    print("\n[STEP 3] Refine:")
    print("    python OmniSV.py refine <out_dir> <model_path> <vcf> <out_vcf> <gpu_id>")
    print("="*70 + "\n")

if __name__ == "__main__":
    main()
